### ISSUE TITLE
Diff-Partial では差分外に誤りがあっても指摘されない

### ISSUE THREAD

**Issue by dorimiamn** [progedu/assert-codeblock-dwango-progedu#16]
意図された仕様かもしれません？

多分大変そうですができれば差分外の誤りも含めて指摘できれば嬉しそうです。

**Comment by dorimiamn** [comment]
Diff も同様

**Comment by oosakiken1** [comment]
実際の運用上だと差分外の間違いがかなり多い印象なので、チェックできると嬉しいです

**Comment by hsjoihs** [comment]
#10 でも言及したように、

## 現状

| コマンド名 | 教材は、差分ある行をすべて含んでいる | 教材は、差分のない行をすべて含んでいる |
|-----------|---------------|-----------------------------|
| diff | true | true |
| diff-partial | false | false  |

## ほしい

| コマンド名 | 教材は、差分ある行をすべて含んでいる | 教材は、差分のない行をすべて含んでいる |
|-----------|---------------|-----------------------------|
| diff | true | true |
| A | true | false  |
| B | false | false  |

という認識で問題ないですかね？

**Comment by dorimiamn** [comment]
すみません、例を載せておくべきでした 🙇 

私の認識が合っていれば、 #10 で言及されている内容とは異なる事象かと思います。

#10 の内容は diff-partial コマンドでは全ての diff を含んでいない場合にもテストが通ってしまうため、指定されたファイル間の差分が教材のコードブロック中に全て含まれている場合と含まれていない場合とでコマンドを分けようというものと認識しています。

今回の場合はそもそも diff 外においてコードブロックとサンプルファイルで差異が生じているにも関わらず指摘されないという形です。

diff コマンドにおいて、例えば以下のような場合に指摘されません。

教材側コードブロック

```diff
 "use stri
-import dc from "damage-calc";
+import $ from "jquery";
```

旧サンプル
```js
"use strict";
import dc from "damage-calc";
```

新サンプル

```js
"use strict";
import $ from "jquery";
```

これらのコードでは、diff 外の部分である 1 行目が一致していないにも関わらず、assert-codeblock は指摘しません。

これは diff-partial コマンドにおいても同様です。

**Comment by hsjoihs** [comment]
なるほど！　確かにこれは指摘されるべきですね
