### ISSUE TITLE
CI に組み込んで使うときのための手引き documentation

### ISSUE THREAD

**Issue by hsjoihs** [progedu/assert-codeblock-dwango-progedu#26]
CI 内に組み込んで使う際にも便利となるように #18 https://github.com/progedu/assert-codeblock-dwango-progedu/pull/25 で @dorimiamn さんにだいぶ調整していただいたので、「このように設定すると、CI で便利に使える」を説明する documentation があるとよいと思いました。

README.md の中に書いていただいてもいいですし、README_for_ci.md などを作っていただいて README.md からリンクを貼るというのでもよいと思います。

**Comment by dorimiamn** [comment]
確かに documentation があったほうが親切ですね。

代表的な利用例は README.md に書いて、細かいものは CI 用の md にまとめようと思います！
